# Generated by Django 4.1.7 on 2023-03-18 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(error_messages={'unique': 'Nombre duplicado.'}, max_length=300, unique=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name', '-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(error_messages={'unique': 'Nombre duplicado.'}, max_length=300, unique=True)),
                ('hidden', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
            options={
                'ordering': ['name', '-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
